import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ThemeInitializer} from "./themeInit";
import {FloatingNav} from "@/components/ui/floating-navbar";
import { Home, Info, Phone } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  {
    name: "Home",
    link: "/home",
    icon: <Home size={16} />, // ✅ Now it's a JSX.Element
  },
  {
    name: "About",
    link: "/about",
    icon: <Info size={16} />,
  },
  {
    name: "Contact",
    link: "/contact",
    icon: <Phone size={16} />,
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <ThemeInitializer />
        <FloatingNav navItems={navItems} />
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
